name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Unittest
        run: |
          make test

      - name: Integration Test
        env:
          TEST_DATABEND_DSN: "databend://databend:databend@localhost:8000/default?sslmode=disable"
        run: |
          make integration
