name: Release

on:
  push:
    paths:
      - 'version.go'
      - '.github/workflows/release.yaml'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      VERSION: 0.6.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Build
        run: go build -v ./...

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${{ env.VERSION }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false